services:
  peacher:
    build: ./peacher
    container_name: peacher 
    ports: 
      - "8080:8080"
    env_file:
      - ./peacher/.env
    
  client:
    build: ./web
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - peacher
  
  ngrok:
    image: ngrok/ngrok
    container_name: peacher-ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    command: http --host-header=client:80 client:80
    depends_on:
      - client