version: "3.8"

services:
  backend:
    build: ./peacher
    container_name: peacher 
    ports: 
      - "8080:8080"
    env_file:
      - ./peacher/.env
    
  frontend:
    build: ./web
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - peacher